---
title: "Senior Project: Map Digitalization through Historical Journal"
author: "M Ilham AR Santoso"
date: "04/01/2024"
output: html_document
---

```{r load-packages}
#install.packages("tidyverse")
library(tidyverse)
#install.packages("readxl")
library(readxl)
library("lubridate")
#install.packages("stringr")
library("stringr")
#install.packages("dplyr")
library("dplyr")
#install.packages("maps")
library(maps)
```

```{r import-datasets}
journal_1871_1872 <- read_excel("Dataset/journal_1871_1872.xlsx")
journal_1873 <- read_excel("Dataset/journal_1873.xlsx")
journal_1874 <- read_excel("Dataset/journal_1874.xlsx")
journal_1875 <- read_excel("Dataset/journal_1875.xlsx")
journal_1876 <- read_excel("Dataset/journal_1876.xlsx")
journal_1877 <- read_excel("Dataset/journal_1877.xlsx")
journal_1878 <- read_excel("Dataset/journal_1878.xlsx")
journal_1879 <- read_excel("Dataset/journal_1879.xlsx")
journal_1880 <- read_excel("Dataset/journal_1880.xlsx")
journal_1881 <- read_excel("Dataset/journal_1881.xlsx")
journal_1882 <- read_excel("Dataset/journal_1882.xlsx")
journal_1883 <- read_excel("Dataset/journal_1883.xlsx")
journal_1884 <- read_excel("Dataset/journal_1884.xlsx")
journal_1885 <- read_excel("Dataset/journal_1885.xlsx")
journal_1886 <- read_excel("Dataset/journal_1886.xlsx")
location_coordinates <- read_excel("Dataset/location_coordinates.xlsx")
```


```{r bind-rows}
journal_1871_1872$journal <- 1
journal_1873$journal <- 2
journal_1874$journal <- 3
journal_1875$journal <- 4
journal_1876$journal <- 5
journal_1877$journal <- 6
journal_1878$journal <- 7
journal_1879$journal <- 8
journal_1880$journal <- 9
journal_1881$journal <- 10
journal_1882$journal <- 11
journal_1883$journal <- 12
journal_1884$journal <- 13
journal_1885$journal <- 14


journals <- dplyr::bind_rows(journal_1871_1872, journal_1873, journal_1874, 
                             journal_1875, journal_1876, journal_1877, 
                             journal_1878, journal_1879, journal_1880, 
                             journal_1881, journal_1882, journal_1883,
                             journal_1884, journal_1885)
```

```{r select-data}
journals_subset <- journals %>%
  select(date_mdy, journal_entry, location) %>%
  filter(location != "NA") %>%
  separate_longer_delim(location, delim = ", ") %>%
  separate_longer_delim(location, delim = ",") 
```

```{r mutate-data}
journals_subset <- journals_subset  %>%
  mutate(date_mdy = mdy(date_mdy),
           year = year(date_mdy),
           month = month(date_mdy))
```

```{r show-location}
journals_subset_loc <- journals_subset  %>%
  count(location) %>%
  arrange(desc(n))
```

```{r group-by-year}
journals_subset_loc_year <- journals_subset %>%
  mutate(year = case_when(year %in% 181 ~ 1881, TRUE ~ year)) %>%
  group_by(year, month) %>%
  count(location)
```

```{r loc-winter-hb}
journals_subset %>%
  filter(location == "Winter Harbor")
```

```{r database-longlat}
location_coordinates <- location_coordinates %>%
  select(location_list, longitude, latitude) %>%
  filter(longitude != "NA") %>%
  rename(location = location_list)
```

```{r join-data-longlat}
loc_df <- journals_subset_loc_year %>%
  left_join(location_coordinates, by = "location") %>%
  drop_na(latitude, year, longitude) %>%
  mutate(latitude = as.numeric(latitude),
         longitude = as.numeric(longitude))
```

```{r export data}
#write.csv(loc_df, file = "loc_df.csv", row.names = FALSE)
```


```{r show-distinct-loc}
journals_subset_loc %>%
  filter(str_detect(string = location, pattern = "Cra")) %>%
  distinct(location)
```

```{r create-thermometer}
journals_subset_thermo <- journals_subset %>%
  filter(str_detect(string = journal_entry, pattern = "Thermometer | thermometer")) %>% # filter rows for mentions of word thermometer
  mutate(temp = as.numeric(str_extract(journal_entry, pattern = '(?<=thermometer |Thermometer )\\d+'))) %>% # extract digits following the word thermometer in a sentence.
  na.omit()
```

```{r ggplot-thermo}
journals_subset_thermo %>%
  filter(location == "Winter Harbor") %>%
  filter(year == c("1879", "1880", "1881", "1882")) %>%
  ggplot(aes(x = date_mdy, y = as.numeric(temp))) +
  geom_point()
```

```{r entry-year-loc}
loc_df_entry <- journals_subset %>%
  left_join(location_coordinates, by = "location") %>%
  drop_na(latitude, year, longitude) %>%
  mutate(latitude = as.numeric(latitude),
         longitude = as.numeric(longitude)) %>%
  na.omit()
```

words to think about why freeland is at the exact location:
- Anchored | anchored
- Discharged | discharged
- wharf
- arriving

```{r desc-entry}
loc_mention <- loc_df_entry %>%
  filter(str_detect(string = journal_entry, pattern = "Anchored|anchored|discharge|discharged|went|wood|wharf|arriving|arrived"), ignore.case = TRUE)
```



```{r mutate-name-loc}
#journals_subset_loc <- journals_subset_loc %>%
  #separate_rows(location, sep = ",") %>%
  #filter(location != c(" ", "?Virgin")) %>%
  #mutate(location = case_when(location %in% c("Cranberry Isles", "Cramberry Isle", "Cranberry Isles", "Cranberrry Isles", "Cranberry Isles ") ~ "Cranberry Isles", TRUE ~ location))
  #mutate(location = case_when(location %in% c("Baker Island", "Bakers Island") ~ "Baker Island"))
```

```{r}
#journals_subset_loc %>%
  #group_by(location) %>%
  #summarize(sum(n))
```
